version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=snapcal
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - MAX_FILE_SIZE=10485760
      - UPLOAD_PATH=./uploads
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snapcal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 